[package]
name = "libR-sys"
version = "0.3.0"
authors = [
    "andy-thomason <andy@andythomason.com>",
    "Thomas Down",
    "Mossa Merhi Reimert <mossa@sund.ku.dk>",
    "Claus O. Wilke <wilke@austin.utexas.edu>",
    "Ilia Kosenkov <ilia.kosenkov.at.gm@gmail.com>",
    "Hiroaki Yutani",
]
edition = "2021"
description = "Low level bindings to the R programming language."
license = "MIT"
links = "R"
documentation = "https://docs.rs/libR-sys/latest/libR_sys/"

[dependencies]

[build-dependencies]
bindgen = { version = "0.63", optional = true }
regex = { version = "1", optional = true }
clang = { version = "2", optional = true, features = ["runtime"] }

[features]
# By default, we use pre-computed bindings that ship with the library. This may fail!
# Turn on the 'use-bindgen' feature to generate bindings on the fly for your platform.
use-bindgen = ["bindgen", "regex", "clang"]
