[package]
name = "libR-sys"
version = "0.1.9"
authors = ["andy-thomason <andy@andythomason.com>"]
edition = "2018"
description = "Low level bindings to the R programming language."
license = "MIT"
links = "R"
documentation = "https://docs.rs/libR-sys/latest/libR_sys/"

[dependencies]

[build-dependencies]
bindgen = "0.53.2"
regex = "1"
